### ISSUE TITLE
Is this support treble?

### ISSUE THREAD

**Issue by jwndud10** [sabpprook/android_device_samsung_astarqlte#2]
Hello
Is this recovery support treble? (especially GSI)
Also, is this recovery compatible for SM-G885S ? (astarqlteskt, SDM660)

**Comment by sabpprook** [comment]
A8 star is not a full treble (a/b slots) device, I'm not sure how will it work with GSI rom but you can have a try with A type of GSI rom.

The kernel that I build for this device tree is a SDM660 based kernel source, I assume that it will work on astarqlteskt as well.

**Comment by jypixel** [comment]
Thanks. Sorry for asking again. Is this recovery support installing image? I'm trying to flash GSI but it says cannot flash image to file systems. What can I do?
