### ISSUE TITLE
help :: build/core/main.mk:21: recipe for target 'run_soong_ui' failed make: *** [run_soong_ui] Error 1

### ISSUE THREAD

**Issue by fangmarisa** [sabpprook/android_device_samsung_astarqlte#4]
use Ubuntu 18 & twrp-8.0
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.0.0
TARGET_PRODUCT=aosp_arm
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPR5.170623.011
OUT_DIR=/home/hot/omni6/out
============================================
ninja: no work to do.
ninja: no work to do.
/home/hot/omni6/out/build-aosp_arm.ninja is missing, regenerating...
[3/240] including ./bootable/recovery/Android.mk ...
/bin/bash: line 0: test: -ge: unary operator expected
bootable/recovery/gui/Android.mk:168: warning: 
****************************************************************************
  Could not find ui.xml for TW_THEME: 
  Set TARGET_SCREEN_WIDTH and TARGET_SCREEN_HEIGHT to automatically select
  an appropriate theme, or set TW_THEME to one of the following:
    landscape_hdpi landscape_mdpi portrait_hdpi portrait_mdpi watch_mdpi
****************************************************************************
bootable/recovery/gui/Android.mk:169: error: Theme selection failed; exiting.
16:44:46 ckati failed with: exit status 1
build/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1

**Comment by sabpprook** [comment]
This branch of device tree was tested on omnirom 7.0 Android source and Ubuntu 16.04 LTS
